language: php

php:
  - 7.3
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - phpenv rehash;
  - composer self-update

install: composer install --no-interaction --no-progress
